import json
import os
import sys
import datetime

import streamlit as st
import plotly.graph_objects as go
import plotly.io as pio

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
import db

st.set_page_config(page_title="Kronos — Reports", layout="wide")
db.init_db()
st.title("Reports")

run_dates = db.all_run_dates()
if not run_dates:
    st.warning("No runs yet.")
    st.stop()

selected_date = st.selectbox("Run date", options=list(reversed(run_dates)), index=0)
signals = db.signals_for_date(selected_date)

BUCKET_NAMES = {
    "daytrade": "Daytrade (1d)",
    "swing": f"Swing ({config.SWING_HORIZON_DAYS}d)",
    "trend_200d": "200-day trend",
    "vol_breakout": "Volatility breakout",
    "mean_reversion": "Mean reversion",
}


def build_report_html(run_date, signals):
    tickers = sorted({s["ticker"] for s in signals})
    sections = []
    for ticker in tickers:
        fc = db.forecast_for(run_date, ticker)
        chart_html = ""
        if fc:
            history_dates = json.loads(fc["history_dates"])
            history_close = json.loads(fc["history_close"])
            forecast_dates = json.loads(fc["forecast_dates"])
            mean_close = json.loads(fc["mean_close"])
            low_close = json.loads(fc["low_close"])
            high_close = json.loads(fc["high_close"])

            fig = go.Figure()
            fig.add_trace(go.Scatter(x=history_dates, y=history_close, mode="lines", name="Actual",
                                      line=dict(color="#1f77b4")))
            fig.add_trace(go.Scatter(x=forecast_dates, y=mean_close, mode="lines", name="Forecast (mean)",
                                      line=dict(color="#ff7f0e")))
            fig.add_trace(go.Scatter(x=forecast_dates + forecast_dates[::-1], y=high_close + low_close[::-1],
                                      fill="toself", fillcolor="rgba(255,127,14,0.2)",
                                      line=dict(color="rgba(0,0,0,0)"), name="10th-90th percentile"))
            fig.update_layout(height=350, margin=dict(l=20, r=20, t=30, b=20),
                               title=f"{ticker} — last close ${fc['last_close']:.2f}")
            chart_html = pio.to_html(fig, full_html=False, include_plotlyjs=False)

        ticker_signals = [s for s in signals if s["ticker"] == ticker]
        rows = "".join(
            f"<tr><td>{BUCKET_NAMES.get(s['bucket'], s['bucket'])}</td><td>{s['label']}</td>"
            f"<td>{s['confidence']}%</td><td>{s['expected_return_pct'] if s['expected_return_pct'] is not None else '-'}</td>"
            f"<td>{s['detail']}</td></tr>"
            for s in ticker_signals
        )
        if not rows:
            rows = "<tr><td colspan='5'><em>No signals triggered</em></td></tr>"

        sections.append(f"""
        <div class="ticker-section">
            <h2>{ticker}</h2>
            {chart_html}
            <table>
                <tr><th>Bucket</th><th>Signal</th><th>Confidence</th><th>Expected Return</th><th>Detail</th></tr>
                {rows}
            </table>
        </div>
        """)

    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Kronos Report — {run_date}</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js"></script>
<style>
  body {{ font-family: -apple-system, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }}
  h1 {{ border-bottom: 2px solid #eee; padding-bottom: 10px; }}
  .ticker-section {{ margin-bottom: 50px; }}
  table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
  th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 14px; }}
  th {{ background: #f5f5f5; }}
  .disclaimer {{ color: #666; font-size: 13px; margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; }}
</style>
</head>
<body>
<h1>Kronos Watchlist Report — {run_date}</h1>
<p>Generated {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
{"".join(sections)}
<p class="disclaimer">Generated by a local Kronos forecasting pipeline. Signals are model output based on
historical price patterns, not investment advice. Labels marked "(unreliable)" exceed a plausibility guardrail
and likely reflect model drift rather than a real signal.</p>
</body>
</html>
"""


st.subheader(f"Preview — {selected_date}")
html = build_report_html(selected_date, signals)
st.components.v1.html(html, height=600, scrolling=True)

st.download_button(
    "Download report (HTML)",
    data=html,
    file_name=f"kronos_report_{selected_date}.html",
    mime="text/html",
)
